//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignementOne.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cours
    {
        public int course_id { get; set; }
        public string course_name { get; set; }
        public Nullable<int> course_grade { get; set; }
      
        public Nullable<int> student_id { get; set; }
        public Nullable<int> staff_id { get; set; }
    
        public virtual Staff_Details Staff_Details { get; set; }
        public virtual Student_Detail Student_Detail { get; set; }
    }
}
